modLoader="javafml"
loaderVersion="[43,)"
license="Maker's Mods License"
[[mods]]
modId="carved_wood"
version="1.0-a-1.20.1"
displayName="Carved Wood"
logoFile="carved_wood_logo.png"
authors="Im_Maker"
credits=""
description='''
Adds new wooden blocks and new variants of existing wooden blocks!
Twitter/X:I_AmMaker
'''
[[dependencies.paintable]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.paintable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.2)"
    ordering="NONE"
    side="BOTH"