plugins {
    id 'net.neoforged.moddev'
}


base {
    archivesName = "${mod_name}-neoforge-${minecraft_version}"
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('../common/src/generated/resources/').getAbsolutePath(), '--existing', file('../common/src/main/resources/').getAbsolutePath()

        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
        }
    }
}

repositories {
    maven {
        url = "https://api.modrinth.com/maven"
    }
    maven {
        // JEI
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven { url = "https://maven.tterrag.com/" }
    maven { url = "https://maven.createmod.net" }
    maven { url = "https://maven.ithundxr.dev/snapshots" }
    maven { url = "https://maven.createmod.net" } // Ponder, Flywheel
}

dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}:sources"
    implementation "net.neoforged:neoforge:${neoforge_version}"

    implementation project(":common")

    //annotationProcessor "net.neoforged:neoforge:${neoforge_version}" // Needed for Mixin processing

    //annotationProcessor("org.spongepowered:mixin:0.8.5") // or latest

    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")

    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")
    //implementation "maven.modrinth:cloth-config:izKINKFg"
    //implementation "maven.modrinth:kubejs:3w2ufpfQ"
    //implementation "maven.modrinth:rhino:KobrWfUm"

    implementation "maven.modrinth:Would:tCzVXIHV"
    implementation "maven.modrinth:moonlight:X7j32itX"
    //implementation "maven.modrinth:supplementaries:B4k8qIJB"
    //implementation "maven.modrinth:amendments:8xf6Wpxs"
    implementation "maven.modrinth:every-compat:tTI0Msfm"

    //implementation "maven.modrinth:visual-workbench:Jy5V5FNj"
    //implementation "maven.modrinth:puzzles-lib:EgWWSAhJ"

    implementation "maven.modrinth:platform:Idu0kQLR"
    implementation "maven.modrinth:vanillabackport:FziQWhG6"
    implementation "maven.modrinth:polymorph:VEburL70"
    implementation "maven.modrinth:crafting-tweaks:9CqWhYyd"
    implementation "maven.modrinth:balm:3XiinKbh"

    implementation "maven.modrinth:my-nethers-delight:n2vJCdff"
    implementation "maven.modrinth:farmers-delight:cYqC3svy"


    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}") { transitive = false }
    implementation("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    implementation("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")

    //compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-$minecraft_version:$flywheel_version")
    //runtimeOnly(jarJar("dev.engine-room.flywheel:flywheel-neoforge-$minecraft_version:$flywheel_version") {
    //    version {
    //        strictly "[1.0,2.0)"
    //        prefer flywheel_version
    //    }
    //})
}

sourceSets {
    main {
        resources {
            srcDirs += [
                    //project(':common').file('src/main/resources').absolutePath,
                    project(':common').file('src/generated/resources').absolutePath
            ]
        }
    }
}

tasks.named('jar', Jar) {
    from project(':common').sourceSets.main.output
}

sourceSets.main.resources { srcDir 'src/generated/resources' }