package net.im_maker.paintable.common.item;

import net.im_maker.paintable.Paintable;
import net.im_maker.paintable.common.block.ModBlocks;
import net.im_maker.paintable.common.item.paint_brushs.*;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.RegistryObject;
import net.minecraft.world.item.Item;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class ModItems {
    public static final DeferredRegister<Item> ITEMS =
            DeferredRegister.create(ForgeRegistries.ITEMS, Paintable.MOD_ID);
    //Paint Brushes
    public static final RegistryObject<Item> PAINT_BRUSH = ITEMS.register("paint_brush", () -> new PaintBrushItem(new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1)));
    public static final RegistryObject<Item> RED_PAINT_BRUSH = ITEMS.register("red_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.RED_PAINTED_PLANKS.get(), ModBlocks.RED_PAINTED_PLANKS_STAIRS.get(), ModBlocks.RED_PAINTED_PLANKS_SLAB.get(), ModBlocks.RED_PAINTED_FENCE.get(), ModBlocks.RED_PAINTED_FENCE_GATE.get(), ModBlocks.RED_PAINTED_BUTTON.get(), ModBlocks.RED_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_RED_PAINTED_LOG.get(), ModBlocks.STRIPPED_RED_PAINTED_WOOD.get(), ModBlocks.RED_PAINTED_BRICKS.get(), ModBlocks.RED_PAINTED_BRICK_STAIRS.get(), ModBlocks.RED_PAINTED_BRICK_SLAB.get(), ModBlocks.RED_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> ORANGE_PAINT_BRUSH = ITEMS.register("orange_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.ORANGE_PAINTED_PLANKS.get(), ModBlocks.ORANGE_PAINTED_PLANKS_STAIRS.get(), ModBlocks.ORANGE_PAINTED_PLANKS_SLAB.get(), ModBlocks.ORANGE_PAINTED_FENCE.get(), ModBlocks.ORANGE_PAINTED_FENCE_GATE.get(), ModBlocks.ORANGE_PAINTED_BUTTON.get(), ModBlocks.ORANGE_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_ORANGE_PAINTED_LOG.get(), ModBlocks.STRIPPED_ORANGE_PAINTED_WOOD.get(), ModBlocks.ORANGE_PAINTED_BRICKS.get(), ModBlocks.ORANGE_PAINTED_BRICK_STAIRS.get(), ModBlocks.ORANGE_PAINTED_BRICK_SLAB.get(), ModBlocks.ORANGE_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> YELLOW_PAINT_BRUSH = ITEMS.register("yellow_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.YELLOW_PAINTED_PLANKS.get(), ModBlocks.YELLOW_PAINTED_PLANKS_STAIRS.get(), ModBlocks.YELLOW_PAINTED_PLANKS_SLAB.get(), ModBlocks.YELLOW_PAINTED_FENCE.get(), ModBlocks.YELLOW_PAINTED_FENCE_GATE.get(), ModBlocks.YELLOW_PAINTED_BUTTON.get(), ModBlocks.YELLOW_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_YELLOW_PAINTED_LOG.get(), ModBlocks.STRIPPED_YELLOW_PAINTED_WOOD.get(), ModBlocks.YELLOW_PAINTED_BRICKS.get(), ModBlocks.YELLOW_PAINTED_BRICK_STAIRS.get(), ModBlocks.YELLOW_PAINTED_BRICK_SLAB.get(), ModBlocks.YELLOW_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> LIME_PAINT_BRUSH = ITEMS.register("lime_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.LIME_PAINTED_PLANKS.get(), ModBlocks.LIME_PAINTED_PLANKS_STAIRS.get(), ModBlocks.LIME_PAINTED_PLANKS_SLAB.get(), ModBlocks.LIME_PAINTED_FENCE.get(), ModBlocks.LIME_PAINTED_FENCE_GATE.get(), ModBlocks.LIME_PAINTED_BUTTON.get(), ModBlocks.LIME_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_LIME_PAINTED_LOG.get(), ModBlocks.STRIPPED_LIME_PAINTED_WOOD.get(), ModBlocks.LIME_PAINTED_BRICKS.get(), ModBlocks.LIME_PAINTED_BRICK_STAIRS.get(), ModBlocks.LIME_PAINTED_BRICK_SLAB.get(), ModBlocks.LIME_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> GREEN_PAINT_BRUSH = ITEMS.register("green_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.GREEN_PAINTED_PLANKS.get(), ModBlocks.GREEN_PAINTED_PLANKS_STAIRS.get(), ModBlocks.GREEN_PAINTED_PLANKS_SLAB.get(), ModBlocks.GREEN_PAINTED_FENCE.get(), ModBlocks.GREEN_PAINTED_FENCE_GATE.get(), ModBlocks.GREEN_PAINTED_BUTTON.get(), ModBlocks.GREEN_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_GREEN_PAINTED_LOG.get(), ModBlocks.STRIPPED_GREEN_PAINTED_WOOD.get(), ModBlocks.GREEN_PAINTED_BRICKS.get(), ModBlocks.GREEN_PAINTED_BRICK_STAIRS.get(), ModBlocks.GREEN_PAINTED_BRICK_SLAB.get(), ModBlocks.GREEN_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> CYAN_PAINT_BRUSH = ITEMS.register("cyan_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.CYAN_PAINTED_PLANKS.get(), ModBlocks.CYAN_PAINTED_PLANKS_STAIRS.get(), ModBlocks.CYAN_PAINTED_PLANKS_SLAB.get(), ModBlocks.CYAN_PAINTED_FENCE.get(), ModBlocks.CYAN_PAINTED_FENCE_GATE.get(), ModBlocks.CYAN_PAINTED_BUTTON.get(), ModBlocks.CYAN_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_CYAN_PAINTED_LOG.get(), ModBlocks.STRIPPED_CYAN_PAINTED_WOOD.get(), ModBlocks.CYAN_PAINTED_BRICKS.get(), ModBlocks.CYAN_PAINTED_BRICK_STAIRS.get(), ModBlocks.CYAN_PAINTED_BRICK_SLAB.get(), ModBlocks.CYAN_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> LIGHT_BLUE_PAINT_BRUSH = ITEMS.register("light_blue_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.LIGHT_BLUE_PAINTED_PLANKS.get(), ModBlocks.LIGHT_BLUE_PAINTED_PLANKS_STAIRS.get(), ModBlocks.LIGHT_BLUE_PAINTED_PLANKS_SLAB.get(), ModBlocks.LIGHT_BLUE_PAINTED_FENCE.get(), ModBlocks.LIGHT_BLUE_PAINTED_FENCE_GATE.get(), ModBlocks.LIGHT_BLUE_PAINTED_BUTTON.get(), ModBlocks.LIGHT_BLUE_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_LIGHT_BLUE_PAINTED_LOG.get(), ModBlocks.STRIPPED_LIGHT_BLUE_PAINTED_WOOD.get(), ModBlocks.LIGHT_BLUE_PAINTED_BRICKS.get(), ModBlocks.LIGHT_BLUE_PAINTED_BRICK_STAIRS.get(), ModBlocks.LIGHT_BLUE_PAINTED_BRICK_SLAB.get(), ModBlocks.LIGHT_BLUE_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> BLUE_PAINT_BRUSH = ITEMS.register("blue_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.BLUE_PAINTED_PLANKS.get(), ModBlocks.BLUE_PAINTED_PLANKS_STAIRS.get(), ModBlocks.BLUE_PAINTED_PLANKS_SLAB.get(), ModBlocks.BLUE_PAINTED_FENCE.get(), ModBlocks.BLUE_PAINTED_FENCE_GATE.get(), ModBlocks.BLUE_PAINTED_BUTTON.get(), ModBlocks.BLUE_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_BLUE_PAINTED_LOG.get(), ModBlocks.STRIPPED_BLUE_PAINTED_WOOD.get(), ModBlocks.BLUE_PAINTED_BRICKS.get(), ModBlocks.BLUE_PAINTED_BRICK_STAIRS.get(), ModBlocks.BLUE_PAINTED_BRICK_SLAB.get(), ModBlocks.BLUE_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> PURPLE_PAINT_BRUSH = ITEMS.register("purple_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.PURPLE_PAINTED_PLANKS.get(), ModBlocks.PURPLE_PAINTED_PLANKS_STAIRS.get(), ModBlocks.PURPLE_PAINTED_PLANKS_SLAB.get(), ModBlocks.PURPLE_PAINTED_FENCE.get(), ModBlocks.PURPLE_PAINTED_FENCE_GATE.get(), ModBlocks.PURPLE_PAINTED_BUTTON.get(), ModBlocks.PURPLE_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_PURPLE_PAINTED_LOG.get(), ModBlocks.STRIPPED_PURPLE_PAINTED_WOOD.get(), ModBlocks.PURPLE_PAINTED_BRICKS.get(), ModBlocks.PURPLE_PAINTED_BRICK_STAIRS.get(), ModBlocks.PURPLE_PAINTED_BRICK_SLAB.get(), ModBlocks.PURPLE_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> MAGENTA_PAINT_BRUSH = ITEMS.register("magenta_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.MAGENTA_PAINTED_PLANKS.get(), ModBlocks.MAGENTA_PAINTED_PLANKS_STAIRS.get(), ModBlocks.MAGENTA_PAINTED_PLANKS_SLAB.get(), ModBlocks.MAGENTA_PAINTED_FENCE.get(), ModBlocks.MAGENTA_PAINTED_FENCE_GATE.get(), ModBlocks.MAGENTA_PAINTED_BUTTON.get(), ModBlocks.MAGENTA_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_MAGENTA_PAINTED_LOG.get(), ModBlocks.STRIPPED_MAGENTA_PAINTED_WOOD.get(), ModBlocks.MAGENTA_PAINTED_BRICKS.get(), ModBlocks.MAGENTA_PAINTED_BRICK_STAIRS.get(), ModBlocks.MAGENTA_PAINTED_BRICK_SLAB.get(), ModBlocks.MAGENTA_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> PINK_PAINT_BRUSH = ITEMS.register("pink_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.PINK_PAINTED_PLANKS.get(), ModBlocks.PINK_PAINTED_PLANKS_STAIRS.get(), ModBlocks.PINK_PAINTED_PLANKS_SLAB.get(), ModBlocks.PINK_PAINTED_FENCE.get(), ModBlocks.PINK_PAINTED_FENCE_GATE.get(), ModBlocks.PINK_PAINTED_BUTTON.get(), ModBlocks.PINK_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_PINK_PAINTED_LOG.get(), ModBlocks.STRIPPED_PINK_PAINTED_WOOD.get(), ModBlocks.PINK_PAINTED_BRICKS.get(), ModBlocks.PINK_PAINTED_BRICK_STAIRS.get(), ModBlocks.PINK_PAINTED_BRICK_SLAB.get(), ModBlocks.PINK_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> BROWN_PAINT_BRUSH = ITEMS.register("brown_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.BROWN_PAINTED_PLANKS.get(), ModBlocks.BROWN_PAINTED_PLANKS_STAIRS.get(), ModBlocks.BROWN_PAINTED_PLANKS_SLAB.get(), ModBlocks.BROWN_PAINTED_FENCE.get(), ModBlocks.BROWN_PAINTED_FENCE_GATE.get(), ModBlocks.BROWN_PAINTED_BUTTON.get(), ModBlocks.BROWN_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_BROWN_PAINTED_LOG.get(), ModBlocks.STRIPPED_BROWN_PAINTED_WOOD.get(), ModBlocks.BROWN_PAINTED_BRICKS.get(), ModBlocks.BROWN_PAINTED_BRICK_STAIRS.get(), ModBlocks.BROWN_PAINTED_BRICK_SLAB.get(), ModBlocks.BROWN_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> BLACK_PAINT_BRUSH = ITEMS.register("black_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.BLACK_PAINTED_PLANKS.get(), ModBlocks.BLACK_PAINTED_PLANKS_STAIRS.get(), ModBlocks.BLACK_PAINTED_PLANKS_SLAB.get(), ModBlocks.BLACK_PAINTED_FENCE.get(), ModBlocks.BLACK_PAINTED_FENCE_GATE.get(), ModBlocks.BLACK_PAINTED_BUTTON.get(), ModBlocks.BLACK_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_BLACK_PAINTED_LOG.get(), ModBlocks.STRIPPED_BLACK_PAINTED_WOOD.get(), ModBlocks.BLACK_PAINTED_BRICKS.get(), ModBlocks.BLACK_PAINTED_BRICK_STAIRS.get(), ModBlocks.BLACK_PAINTED_BRICK_SLAB.get(), ModBlocks.BLACK_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> GRAY_PAINT_BRUSH = ITEMS.register("gray_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.GRAY_PAINTED_PLANKS.get(), ModBlocks.GRAY_PAINTED_PLANKS_STAIRS.get(), ModBlocks.GRAY_PAINTED_PLANKS_SLAB.get(), ModBlocks.GRAY_PAINTED_FENCE.get(), ModBlocks.GRAY_PAINTED_FENCE_GATE.get(), ModBlocks.GRAY_PAINTED_BUTTON.get(), ModBlocks.GRAY_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_GRAY_PAINTED_LOG.get(), ModBlocks.STRIPPED_GRAY_PAINTED_WOOD.get(), ModBlocks.GRAY_PAINTED_BRICKS.get(), ModBlocks.GRAY_PAINTED_BRICK_STAIRS.get(), ModBlocks.GRAY_PAINTED_BRICK_SLAB.get(), ModBlocks.GRAY_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> LIGHT_GRAY_PAINT_BRUSH = ITEMS.register("light_gray_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.LIGHT_GRAY_PAINTED_PLANKS.get(), ModBlocks.LIGHT_GRAY_PAINTED_PLANKS_STAIRS.get(), ModBlocks.LIGHT_GRAY_PAINTED_PLANKS_SLAB.get(), ModBlocks.LIGHT_GRAY_PAINTED_FENCE.get(), ModBlocks.LIGHT_GRAY_PAINTED_FENCE_GATE.get(), ModBlocks.LIGHT_GRAY_PAINTED_BUTTON.get(), ModBlocks.LIGHT_GRAY_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_LIGHT_GRAY_PAINTED_LOG.get(), ModBlocks.STRIPPED_LIGHT_GRAY_PAINTED_WOOD.get(), ModBlocks.LIGHT_GRAY_PAINTED_BRICKS.get(), ModBlocks.LIGHT_GRAY_PAINTED_BRICK_STAIRS.get(), ModBlocks.LIGHT_GRAY_PAINTED_BRICK_SLAB.get(), ModBlocks.LIGHT_GRAY_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));
    public static final RegistryObject<Item> WHITE_PAINT_BRUSH = ITEMS.register("white_paint_brush", () -> new DippedPaintBrushItem(ModBlocks.WHITE_PAINTED_PLANKS.get(), ModBlocks.WHITE_PAINTED_PLANKS_STAIRS.get(), ModBlocks.WHITE_PAINTED_PLANKS_SLAB.get(), ModBlocks.WHITE_PAINTED_FENCE.get(), ModBlocks.WHITE_PAINTED_FENCE_GATE.get(), ModBlocks.WHITE_PAINTED_BUTTON.get(), ModBlocks.WHITE_PAINTED_PRESSURE_PLATE.get(), ModBlocks.STRIPPED_WHITE_PAINTED_LOG.get(), ModBlocks.STRIPPED_WHITE_PAINTED_WOOD.get(), ModBlocks.WHITE_PAINTED_BRICKS.get(), ModBlocks.WHITE_PAINTED_BRICK_STAIRS.get(), ModBlocks.WHITE_PAINTED_BRICK_SLAB.get(), ModBlocks.WHITE_PAINTED_BRICK_WALL.get(), new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).stacksTo(1).durability(16)));

    public static void register(IEventBus eventBus) {
        ITEMS.register(eventBus);
    }

}